### PR TITLE
Enhancements r2

### PR DESCRIPTION
**Pull request by marianavillarp**
- Updates in README.md
- Change `docker` as host from test playbooks
- Remove travis files
- Playbook enhancements

### CODE REVIEW

**Review by JamRamPage — COMMENTED** [review]
@stewmcl the test playbooks all work successfully for this except "test_web_console.yml" which fails with the following error. Ever seen it before?


Screenshot 2023-02-10 at 14 12 24

**Review by JamRamPage — APPROVED** [review]
Despite that issue in testing, the web console works. The changes look good to me.

**Comment by stewmcl** [comment]
The web console issue isn't actually a problem with the console itself, more that the test of wether the old registry file exists is failing (indicating it can't find the file)

**Review by stewmcl — APPROVED** [review]
The changes look good, and the "test old registry exists" shouldn't have any impact on wether the console runs or not

**Pull request merged**
