### PR TITLE
Refactor queue manager

### PR DESCRIPTION
**Pull request by stewmcl**

### CODE REVIEW

**Comment by bimsara-yasitha01** [comment]
Hi Stewart, just checking something I noticed whilst testing your PR, the runmqsc task is skipped (where on `main` the status is 'ok'). Is this expected?

main:
image

your branch:
image

**Comment by stewmcl** [comment]
@bimsara-yasitha01  Yes, the task being skipped is to be expected

**Review by marianavillarp — COMMENTED** [review]
Similar to @bimsara-yasitha01 the `Run MQSC` task was skipped on a new machine with no previous configuration. Checked on the machine though and the queues have been created in runmqsc, so the task does run (it just shows as skipped). Everything else has worked on Ubuntu* as expected. 

*Tried on RH accidentally and it failed- seems like it is because the RH installation changes are not in this branch yet. 

```
3 : display qlocal(*)
AMQ8409I: Display Queue details.
   QUEUE(DEV.DEAD.LETTER.QUEUE)            TYPE(QLOCAL)
AMQ8409I: Display Queue details.
   QUEUE(DEV.QUEUE.1)                      TYPE(QLOCAL)
AMQ8409I: Display Queue details.
   QUEUE(DEV.QUEUE.2)                      TYPE(QLOCAL)
AMQ8409I: Display Queue details.
   QUEUE(DEV.QUEUE.3)                      TYPE(QLOCAL)
```

**Comment by stewmcl** [comment]
Merged main into my branch so redhat should *hopefully* work now.
As for the MQSC being "skipped" but still working, looking into it now

**Comment by JamRamPage** [comment]
Are we expecting MQSC to be run even with state=present?
image

Because the final test in "test_present_qmgr.yml" quite clearly implies that if "mqsc_file" is provided with state: present, then we should _**not**_ run the MQSC:
image

I can fix this in my most recent PR by changing the test or the module.

**Comment by JamRamPage** [comment]
Looks like #13 requested the ability to run MQSC then stop the qmgr in one go - I will change the test appropriately.

**Pull request merged**
