### PR TITLE
Linux Fixpack installation

### PR DESCRIPTION
**Pull request by bimsara-yasitha01**
Provides support for Ubuntu and RHEL fixpack upgrades

### CODE REVIEW

**Review by stewmcl — APPROVED** [review]
👍 Changes are looking good!

**Comment by JamRamPage** [comment]
Just a few questions. I see that this is similar to the installmq role.

- [ ] Do we need a hyphen for "**<fixpack-zip>**" in playbooks/mq-upgrade.yml. Is this a variable that the user adds with extra-vars in their command to run this playbook?
- [ ] Below, I see us refer to "fixpack_tar" - can we be consistent with tar and zip and call it fixpack-zip above?
- [ ] I see that Linux_installmq.yml includes the following lines in two tasks. Are they not needed here?
  when:
    - '"MQSeriesRuntime" not in ansible_facts.packages'
    - '"ibmmq-runtime" not in ansible_facts.packages'

- [ ] Is there a difference in how our code treats "Linux x86" to "Linux"?

**Comment by bimsara-yasitha01** [comment]
Hi @JamRamPage, thanks for the comments:

> Do we need a hyphen for "" in playbooks/mq-upgrade.yml. Is this a variable that the user adds with extra-vars in their command to run this playbook?

No, in the role the variables `fixpack_zip` and `fixpack_dir` are derived from the user-provided `fixpack_local` variable, so don't need to be supplied to the role as well.

> Below, I see us refer to "fixpack_tar" - can we be consistent with tar and zip and call it fixpack-zip above?

Good spot, I've changed `fixpack_tar` to `fixpack_zip` to avoid any errors.

>  I see that Linux_installmq.yml includes the following lines in two tasks. Are they not needed here?

I've now added the inverse of that condition into the upgrade role (e.g. only run when mq is already installed) to avoid errors when a developer tries to run an upgrade without an existing MQ base installation (unlikely scenario but it's covered now nonetheless).

> Is there a difference in how our code treats "Linux x86" to "Linux"?

Not at the moment. If I'm following your thread you're talking about the naming of the tasks? If so, I've renamed `Linux_x86_64_applyfixpack.yml` to `Linux_applyfixpack.yml`.

**Comment by bimsara-yasitha01** [comment]
@JamRamPage 

1. `fixpack_local` in this playbook just shows an example path, there is no default location that we can provide to the developer as all fixpacks will be grabbed from Fix Central. See [AIX_ppc64le_downloadmq.yml](https://github.com/ibm-messaging/mq-ansible/blob/main/roles/downloadmq/tasks/AIX_ppc64le_downloadmq.yml), [Linux_s390x_downloadmq.yml](https://github.com/ibm-messaging/mq-ansible/blob/main/roles/downloadmq/tasks/Linux_s390x_downloadmq.yml). The hypen (and the rest of that variable) is just a placeholder.

1. Done.

**Review by JamRamPage — APPROVED** [review]
Ok, that looks excellent. I see that mq-upgrade.yml is just a sample yml file.

**Pull request merged**
