### PR TITLE
Documentation for applying fix packs

### PR DESCRIPTION
**Pull request by bimsara-yasitha01**
Explanation of pre-reqs and steps for running the `mq-upgrade.yml` sample playbook.

### CODE REVIEW

**Comment by bimsara-yasitha01** [comment]
@marianavillarp busted! Have edited :)

**Review by marianavillarp — APPROVED** [review]
thanks! 😄

**Comment by JamRamPage** [comment]
It looks mostly good, though why is the first link in the docs for the mq-upgrade.yml that's in your fork of the repository?

image

**Comment by bimsara-yasitha01** [comment]
@JamRamPage good spot, have updated now :)

**Pull request merged**
