### PR TITLE
Ansible Lint Fixes

### PR DESCRIPTION
**Pull request by bimsara-yasitha01**
Merge ready PR for #47

### CODE REVIEW

**Review by stewmcl — APPROVED** [review]
Fixes look good, yeah i'm happy to approve this 👍

**Review by marianavillarp — COMMENTED** [review]
Changes look good but when testing it on windows few things came up:

- tests have broken for windows as `become:true` tries to run as sudo which returns error 

```shell
The powershell shell family is incompatible with the sudo become plugin
```

- To fix this playbooks should have `become: false` but not sure if this will break tests on unix based platforms. 

- Playbooks now can be run, however roles can't due to `The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'dict object' has no attribute 'PATH'` error. Not sure yet why this is happening?

- Also noticed that the script to configure windows hosts have changed so if its okay can I update the docs in this branch with the correct one?

**Comment by benbrunyee** [comment]
Closes #47

**Review by marianavillarp — APPROVED** [review]

**Comment by bimsara-yasitha01** [comment]
For reference, following investigation we have found that all points but the last from Mariana's review are problems already existing on the main branch:

> Changes look good but when testing it on windows few things came up:
> 
>     * tests have broken for windows as `become:true` tries to run as sudo which returns error
> 
> 
> ```shell
> The powershell shell family is incompatible with the sudo become plugin
> ```
> 
>     * To fix this playbooks should have `become: false` but not sure if this will break tests on unix based platforms.
> 
>     * Playbooks now can be run, however roles can't due to `The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'dict object' has no attribute 'PATH'` error. Not sure yet why this is happening?
> 
>     * Also noticed that the script to configure windows hosts have changed so if its okay can I update the docs in this branch with the correct one?

I've updated the doc link to the configure windows script as per the last point. Merging this PR in and will raise new issues to resolve the existing bugs we've found

**Pull request merged**
